version: "3.8"

services:

  # Webサーバー
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile-client
    tty: true
    volumes:
      - ./client:/client
    env_file:
      - .env
    environment:  #* 環境変数の名称変換
      # Socket.ioを使用したAPIサーバーとの接続に使用
      - NEXT_PUBLIC_SERVER_HOST=${SERVER_HOST}
      - NEXT_PUBLIC_SERVER_PORT=${SERVER_PORT}

      # レンダリングオプション
      - WATCHPACK_POLLING=true
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    command: sh -c "${CLIENT_COMMAND}"

  # APIサーバー
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile-server
    tty: true
    volumes:
      - ./server:/server
    env_file:
      - .env
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    command: sh -c "${SERVER_COMMAND}"