import Head from 'next/head'
import styles from '@/styles/Home.module.scss'
import io from "socket.io-client"
import config from '@/config'
import { useState } from 'react'

// socket-apiへの接続
const socket = io(`http://${config.server.host}:${config.server.port}`)

// socket-apiから送信されるメッセージデータの型
interface socketMessageData {
  message: string
}

export default function Home() {
  // メッセージ
  const [text, setText] = useState("")

  // メッセージのログ
  const [messageLog, setMessageLog] = useState<socketMessageData[]>([])

  // socket-apiにテキストを送信
  const handleSubmit = () => {
    socket.emit("send_message", { message: text })
    setText("")
  }

  // socket-apiからメッセージを受け取った時にログを追加する
  socket.on("recived_message", (data: socketMessageData) => {
    setMessageLog([...messageLog, data])
  })

  return (
    <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className={styles.main}>
      <form onSubmit={(e) => e.preventDefault()}>
        <input type="text" value={text} onChange={(e) => setText(e.target.value)} placeholder="メッセージを記入" autoComplete="off" />
        <input type="submit" onClick={() => handleSubmit()} />
      </form>
      <div className={styles.message_log}>
        {messageLog.map((chat) => (
          <div key={chat.message}>{chat.message}</div>
        ))}
      </div>
    </main>
    </>
  )
}
